# Generated by Django 5.0.1 on 2024-03-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_address_line_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount_paid',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
